### ISSUE TITLE
Misspelled word "programming"

### ISSUE THREAD

**Issue by DominikPalo** [oaki/palkosazeni_sk#1]
The correct form is "programming" instead of "programing" ;)

https://github.com/oaki/palkosazeni_sk/blob/bd06ada55a8d9c6742b8cc7e490e56e71de6cfe5/app/presenters/templates/%40layout.latte#L128

**Comment by DominikPalo** [comment]
Here is my PR (fix): https://github.com/oaki/palkosazeni_sk/pull/2

**Comment by oaki** [comment]
Thx ;)
